### ISSUE TITLE
sessions -i bug??

### ISSUE THREAD

**Issue by newjacks** [hanshoffman/crispy-fortnight#19]
when run sessions -i commond 
error :
[!] dictionary update sequence element #0 has length 4; 2 is required

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 305, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 535, in _handle_call
    return self._local_objects[oid](*args, **dict%28kwargs%29)
  File "<string>", line 3, in _rinteract
ValueError: dictionary update sequence element #0 has length 4; 2 is required

**Comment by rhoskal** [comment]
yes I am aware of this bug @newjacks. i'm still working this... any pulls are greatly appreciated.
